require("dotenv").config();

// It must be generated by generate-keys.js script
const jwks = require("./jwks.json");
const { getNFTMetadata } = require("./web3");

module.exports = {
  clients: [],
  interactions: {
    url(ctx, interaction) {
      return `/interaction/${interaction.uid}`;
    },
  },
  async findAccount(ctx, sub) {
    // sub is "/"-separated string
    const [nft_contract_address, nft_item_id] = sub.split("/");

    const nft_metadata = await getNFTMetadata(
      nft_contract_address,
      nft_item_id
    );
    return {
      accountId: sub,
      async claims() {
        return {
          sub,
          nft_contract_address,
          nft_item_id,
          nft_metadata,
        };
      },
    };
  },
  responseTypes: ["id_token"],
  cookies: {
    keys: process.env.OIDCP_SECURE_KEYS.split(","),
  },
  claims: {
    openid: ["sub", "nft_contract_address", "nft_item_id", "nft_metadata"],
  },
  features: {
    devInteractions: {
      enabled: false,
    },
  },
  jwks,
};
